### PR TITLE
babel-core: try to fix one part of travis build

### PR DESCRIPTION
**Pull request by ericmdantas**

### CODE REVIEW

**Comment by georgeedwards** [comment]
@ericmdantas Would you mind taking a look at [this](https://travis-ci.org/georgeedwards/Gen-App/builds/120269441), the unit tests seem to be failing?

**Comment by ericmdantas** [comment]
Sure!

**Comment by georgeedwards** [comment]
@ericmdantas Awesome, thanks!

**Comment by ericmdantas** [comment]
Let's track it here: https://github.com/georgeedwards/Gen-App/pull/4

**Pull request merged**
