### PR TITLE
some changes: changes procfile, adds .map, changes readme and updates…

### PR DESCRIPTION
**Pull request by ericmdantas**
… travis.yml

### CODE REVIEW

**Comment by georgeedwards** [comment]
Great, Thanks so much for this! I'll look into the `node-gyp` issue. I think the issue is that you need something between 2.5.0 and 3.0.0, it seems that travis is using 3.2.1.

**Comment by ericmdantas** [comment]
I see. `node-gyp` is always a pain, specially when I'm on a PC. If you don't find out what it is, I'll see what I can do - I'm pretty sure there are some work arounds out there.

**Comment by georgeedwards** [comment]
@ericmdantas OK, fixed it! There were a few additional bits required in the travis config file. The build is now running (although failing), if you get a chance to help me get it passing, I would be really grateful.

**Comment by ericmdantas** [comment]
Right, I'll prepare another PR with the fixes.

The chrome one was expected, see: https://github.com/ericmdantas/angular2-typescript-todo/issues/5

As for the `babel/register`, I guess that's supposed to be `babel-core/register`, since we're using babel 6.

**Comment by georgeedwards** [comment]
Awesome, thanks

**Comment by georgeedwards** [comment]
Hi Eric,

Any luck?

**Comment by ericmdantas** [comment]
I'm doing it later today.

**Pull request merged**
